### PR TITLE
initial release of the package-type scaffolder plugin

### PR DESCRIPTION
**Pull request by travi**
i havent added this to the RFC yet, but the more i think about the high-level scaffolding idea, i think it makes the most sense to tackle it in two parts:
* a normal plugin that can be wired in as an option for a type of package-type project
* a wrapper that calls the `project-scaffolder` that provides decisions that choose this as the package-type plugin option and also provides decisions for several other prompts to make it align with a standard config extension project

this implements most of the first bullet

### CODE REVIEW

**Comment by trevtrich** [comment]
It'd be good to chat about this one tomorrow as a "use case". I'm confused on why you named this pr the way you did so I'm thinking I have the wrong idea in my head.

**Comment by travi** [comment]
cool, yeah, this is a pretty direct example of what i have in mind. the bigger trick might be expanding from this example to the generic case to try to make sure we arent being too focused on this example

**Comment by travi** [comment]
@trevtrich not sure that we touched on this very directly tonight, but how does the additional context impact your thoughts on this?

**Comment by trevtrich** [comment]
Definitely helped a fair bit on the goals. I'm still not clear on why the PR says it's a release of the package-type scaffolder plug-in so makes me think I'm missing something.

**Comment by trevtrich** [comment]
Is it just meaning this will be a plug-in that a consuming package type scaffolder could consume?

**Comment by travi** [comment]
the function exported as the named export here as `scaffold` would be available to be injected as a plugin for the group of choices for package-types. other available package-type scaffolder plugins include [these](https://github.com/form8ion/awesome#package-types).

this is only part of the config extension goal of this overall package, since it would also need to export the high-level scaffolder that would pass the `decisions` down to choose this sub-scaffolder from the list of provided package-type scaffolders (as well as instructing the scaffolder to not treat it as a unit/integration tested project, not transpiled project, etc)

**Comment by trevtrich** [comment]
ah, okay i think i get what you mean. definitely some pain getting through shared terminology / naming

**Review by trevtrich — APPROVED** [review]

**Pull request merged**
