### PR TITLE
fix(js-decisions): passed provided decisions through to the js-scaffolder factory

### PR DESCRIPTION
**Pull request by travi**

### CODE REVIEW

**Comment by travi** [comment]
fixes passing the decisions to the js-scaffolder properly. i've gone back and forth a number of times in my head on the right way to thread this through, but was able to prove the correct way through the integration test for the `@pragmatic-divops/cli`

**Review by trevtrich — APPROVED** [review]
👍 seems fair to me. I had some question as to how you would know if you used this what the decisions got passed to, but we only leverage certain decisions per scaffolder so I suppose the same decisions blob can be used for multiple levels.

**Comment by travi** [comment]
> we only leverage certain decisions per scaffolder so I suppose the same decisions blob can be used for multiple levels

yeah, the key is to keep the keys between the scaffolders unique across the scaffolder so that there arent conflicts in the combined decisions map. this was actually the detail mentioned in the other PR about the two `PROJECT_TYPE` question names that resulted in the value change of one of them. hopefully being unique about this wont become too dangerous over time.

**Comment by trevtrich** [comment]
ah, okay that also makes sense in hindsight to what you were pointing out as you mentioned. 👍 all sounds good, and good to know.

**Pull request merged**
